name: Daily Job Change Scraping

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '14'
        postgresql db: job_changes
        postgresql user: postgres
        postgresql password: postgres
    
    - name: Initialize database
      run: |
        psql -U postgres -d job_changes -f init_db.sql
      env:
        PGPASSWORD: postgres
    
    - name: Run scraper
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/job_changes
      run: python run_scraper.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update job changes data" && git push)
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.issue;
          github.rest.issues.create({
            owner: issue.owner,
            repo: issue.repo,
            title: 'Scraping Job Failed',
            body: 'The daily job change scraping workflow failed. Please check the logs for details.'
          });
